services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    environment:
      - SESSION_SECRET=docker_dev_secret_change_in_production
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    volumes:
      - ./:/app
      - /app/venv
      - /app/instance
      - /app/bank_management.db
    command: >
      bash -c "cd /app &&
      pip install -r requirements-local.txt &&
      python -c 'from main import app, db;
      from seed_data import seed_database;
      with app.app_context():
          db.create_all();
          seed_database()' &&
      flask run --host=0.0.0.0 --port=5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005"]
      interval: 30s
      timeout: 10s
      retries: 3
