version: '3.8'

services:
  web:
    build: .
    ports:
      - "5005:5000"
    volumes:
      - ./instance:/app/instance  # Persist SQLite DB
      - ./templates:/app/templates  # Mount templates
      - ./static:/app/static  # Mount static files
    environment:
      - FLASK_ENV=production
      - SESSION_SECRET=your-secret-key-here
