services:
  web:
    build: .
    ports:
      - "5005:5000"
    volumes:
      - ./instance:/app/instance
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - FLASK_APP=main.py  # Add this line
      - FLASK_ENV=production
      - SESSION_SECRET=your-secret-key-here
